version: '3.8'

volumes:
  db:
    name: db

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql:Z
    env_file:
      - .env

  backend-app:
    build: .
    image: spherity_backend:latest
    container_name: spherity_backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure
    links:
      - 'postgres:database'
